use_frameworks!

source'https://git.coding.net/zhangdekai_5111/Thinker.git'#私有repo Spec
source'https://github.com/CocoaPods/Specs.git'#cocoapods公有repo Spec

target 'podTestLibrary_Example' do   #demo 用的
    pod 'podTestLibrary', :path => '../'
#    pod 'podTestLibrary', '~> 0.2.0'

#target 'podTestLibrary_Tests' do    #test 用的
#    inherit! :search_paths
#
#  pod 'Specta'
#  pod 'Expecta'
#  pod 'FBSnapshotTestCase'
#  pod 'Expecta+Snapshots'
#  end
end
